markdown: rdiscount
permalink: /:title/
url: http://www.notebean.com
name: notebean.com
author: EricSu
qq: 124552346
email: ericsu1988@gmail.com
duoshuo: Ricky
#beian: 2057
#weibo: 1377583044
github: 1q84
pygments: true
safe: true
paginate: 20
about: "Let it be,Be it so."
